Vagrant.configure("2") do |config|
    config.vm.define "vagrant"
    config.vm.box = "vagrant_centos6"
    config.vm.box_url = "file://centos6.box"
    config.vm.hostname = "centos6.localdomain"

    config.ssh.forward_agent = "true"
    config.vm.network :private_network, type: "dhcp", auto_config: false

    # Forward X11
    config.ssh.forward_x11 = true
    
    ## Using NFS as it has much better performance
    ## On linux install nfs-kernel-server, MacOS works by default
    ## Will ask for root password to set some things up
    config.vm.synced_folder ".", "/vagrant", :nfs => true


    ## Use this line to forward ports, remember to open local firewall and reload vagrant
    config.vm.network :forwarded_port, guest: 8080, host: 58080, id: "tomcat", auto_correct: true
    config.vm.network :forwarded_port, guest: 9010, host: 59010, id: "tomcat", auto_correct: true



    config.vm.provider :virtualbox do |vb|
        #vb.gui = true
        vb.customize ["modifyvm", :id, "--memory", 1024]
        vb.customize ["modifyvm", :id, "--cpus", 2]
        vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
end
